name: borsh
version: 0.2.0+1
repository: https://github.com/cryptoplease/cryptoplease-dart
description: >-
  Implementation of the borsh serialization scheme

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^2.0.0
  borsh_annotation: ^0.2.0+1
  build: ^2.0.3
  source_gen: ^1.0.3

dev_dependencies:
  build_runner: ^2.0.6
  mews_pedantic: ^0.2.1
  test: ^1.17.10
